#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - policy_api_vars.yml
    - livefire_vars.yml
  tasks:
    - name: Create Security Policy and Groups      
      uri:
        method: PATCH
        url: "https://{{ nsx_node1.hostname }}/policy/api/v1/infra/"
        user: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        body: "{{microsegmentation}}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
        status_code: 200

    - name: Tag VMs via terraform
      terraform:
        project_path: ./terraform-tags
        state: present
