- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create a compute collection fabric template
      nsxt_compute_collection_fabric_templates:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: CC_fabric_template
        cluster_name: "cl1"
        compute_manager_name: VC1
        auto_install_nsx: True
        state: present
