- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create logical router port
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "lrouterport-103"
        resource_type: "LogicalRouterDownLinkPort"
        logical_router_name: "tier-0"
        linked_logical_switch_port_id:
          target_type: "LogicalPort"
          target_id: "fa535fbd-c01f-4536-86e4-36ee3572b6f3"
        subnets:
        - ip_addresses:
          - 192.168.3.1
          prefix_length: 24
        state: "present"
