- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Add fabric node
      nsxt_fabric_nodes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: "HostNode"
        #node_id: "fefc3fed-84d9-4170-bf7c-5d7438ba91e9"
        display_name: "{{item.display_name}}"
        ip_addresses: "{{item.ip_addresses}}"
        os_type: "{{item.os_type}}"
        os_version: "{{item.os_version}}"
        host_credential:
            username: "{{item.host_username}}"
            password: "{{item.host_password}}"
            thumbprint: "{{item.host_thumbprint}}"
        state: "present"
      with_items:
        - "{{fabric_host_nodes}}"
