- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create logical router
      nsxt_logical_routers:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "tier-0"
        edge_cluster_name: "edge-cluster-1"
        router_type: "TIER0"
        high_availability_mode: "ACTIVE_ACTIVE"
        state: "present"
