- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create logical switch
      nsxt_logical_switches:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "ls1"
        replication_mode: SOURCE
        admin_state: UP
        transport_zone_name: "TZ1"
        state: "present"
