- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create a Logical Port
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "logical_port_1"
        logical_switch_name: "ls1"
        attachment:
          attachment_type: "VIF"
          id: "vif2"
        admin_state: "UP"
        state: "present"
