- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Add Static Routes on a Logical Router
      nsxt_logical_router_static_routes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        logical_router_name: "tier-0"
        next_hops:
        - administrative_distance: '2'
          ip_address: 192.168.200.254
        network: 192.168.200.0/24
        state: "present"
