- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create transport node profile 
      nsxt_transport_node_profiles:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: TransportNodeProfile
        display_name: "{{item.display_name}}"
        description: NSX configured Test Transport Node Profile
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        transport_zone_endpoints: "{{item.transport_zone_endpoints}}"
        state: present
      with_items:
        - "{{transport_node_profiles}}"
